### ISSUE TITLE
Open in Sourcegraph doesn't work

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph-vscode-DEPRECATED#11]
![screen recording 2018-07-10 at 02 00 pm](https://user-images.githubusercontent.com/754768/42537469-cb0801f0-8449-11e8-81bb-9d7b98d2895e.gif)

I wonder if an extension API changed.

**Comment by emidoots** [comment]
The chrome console says `package.json` is missing:

![image](https://user-images.githubusercontent.com/3173176/42537930-2f8ab2a2-844b-11e8-9c9a-009422da7a93.png)

I suspect this regression was introduced by @felixfbecker's change in: https://github.com/sourcegraph/sourcegraph-vscode/commit/62735759d671be4cf9af6852346fef7361999916#diff-45327f86d4438556066de133327f4ca2R7

If so, the extension has been broken for almost a month.

**Comment by nicksnyder** [comment]
Confirmed working, thanks!
