### ISSUE TITLE
Feature: Copy link to clipboard

### ISSUE THREAD

**Issue by ajhyndman** [sourcegraph/sourcegraph-vscode-DEPRECATED#194]
Suggestion: New Command `Sourcegraph: Copy link`

For my workflows, I often want to use SourceGraph as a means of sharing a code reference, without necessarily wanting to open the link myself.  I think it would be useful to have a sibling command to `Sourcegraph: Open` that gets the same URL, but copies it to my system clipboard, instead of launching in a browser.

**Comment by abeatrix** [comment]
Hi @ajhyndman we have implemented this in the[ latest version of our VS Code extension](https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph). Please feel free to reopen this issue if that is not something you have in mind 😄
