### ISSUE TITLE
"File does not exist" when trying "Sourcegraph: open" on Windows

### ISSUE THREAD

**Issue by djpereira** [sourcegraph/sourcegraph-vscode-DEPRECATED#22]
When you use the sourcegraph:open (Alt+A) command on Windows, the browser opens at:

https://sourcegraph.mycompany.com/github.com/mycompany/myrepo/-/blob/src%5Cactions%5Cauth.js#L29:22

Instead of:
https://sourcegraph.mycompany.com/github.com/mycompany/myrepo/-/blob/src/actions/auth.js#L29:22

I think you need to replace the windows backslash for a forward slash for all paths.

**Comment by sqs** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph-vscode/pull/23 by @djpereira, released in 1.0.14. Thank you for the contribution, @djpereira! :tada:
