### ISSUE TITLE
Is the web-based vs code open source?

### ISSUE THREAD

**Issue by cwtuan** [sourcegraph/sourcegraph-vscode-DEPRECATED#4]
Since VS code is built with electron, how do you get rid of electron and make it run in browser?

![image](https://user-images.githubusercontent.com/3455798/29817250-f72fc748-8ce9-11e7-9310-2e2bb22e64c9.png)

**Comment by felixfbecker** [comment]
Hi @cwtuan, Electron is just an environment that combines a DOM API with the NodeJS API. By replacing NodeJS API calls it is possible to run vscode in the browser.
