### ISSUE TITLE
Allow user to configure repo name

### ISSUE THREAD

**Issue by phrohdoh** [sourcegraph/sourcegraph-vscode-DEPRECATED#8]
Currently opening a file in sourcegraph attempts to open `<url>/<host>/<filepath>` (ex: `http://localhost:1234/bitbucket.org/foo/bar/myfile`).

Repositories in sourcegraph are not necessarily configured with this naming scheme.

In fact in my local instance the repo name is just `foo/bar` so I must manually remove the `bitbucket.org/` segment each time.

**Comment by sqs** [comment]
Thanks for filing. This is a known issue that we hope to address soon.

**Comment by sqs** [comment]
Tentatively we plan to address this in November as part of the "More robust repository syncing" project on our roadmap: https://docs.sourcegraph.com/dev/roadmap#november-2018.

**Comment by jeduan** [comment]
Hi! Just wanted to add a datapoint that we currently have the same issue, and I believe it's been reported on #2 as well. We have a hosted Sourcegraph installation and at least 100 engineers using VSCode.

**Comment by felixfbecker** [comment]
We now have a GraphQL API for resolving clone URLs to repos, so this should be possible without configuration

**Comment by jeduan** [comment]
@felixfbecker Is this a feature that needs to be added to the extension? Couldn't find any references on the code or docs.

**Comment by sqs** [comment]
This is a feature that needs to be added to the extension. It is not something you can configure yet, unfortunately. Sorry for the delay here.

**Comment by jeduan** [comment]
@sqs thanks for the update! We love sourcegraph at work and this would make our life so much better

**Comment by devajmitra** [comment]
Any update on this?

**Comment by mtbentley** [comment]
I have a super naive implementation of this here: https://github.com/sourcegraph/sourcegraph-vscode/compare/master...matthewbentley:better_self_hosted_support

**Comment by keegancsmith** [comment]
@sqs I don't think I'm a good owner for this since I don't use vscode / typescript. Re-assigning to you to triage.
